# fly.toml app configuration file generated for tok on 2025-12-24T15:06:02Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tok'
primary_region = 'iad'

[build]


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
